server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

swagger:
  resourcePackage: io.stargate.web.resources
  title: "Stargate REST API"
  version: "2.0.0"

